services:
  auction-mongo-express:
    ports:
      - "5053:8081"

  user-phpmyadmin:
    ports:
      - "5051:80"

  invoice-mongo-express:
    ports:
      - "5052:8081"

  pgadmin:
    ports:
      - "5050:80"
