server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.ryannoah: TRACE

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:userdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:auction}
    password: ${DB_PASSWORD:auction}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  enable-hateoas: false
