server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:auction-test-db;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    locations: classpath:db/migration

services:
  user-service:
    base-url: http://localhost:18081
  listing-service:
    base-url: http://localhost:18082
  invoice-service:
    base-url: http://localhost:18083
