server:
  port: 0

spring:
  data:
    mongodb:
      database: auction-test-db

services:
  user-service:
    base-url: http://localhost:18081
  listing-service:
    base-url: http://localhost:18082
  invoice-service:
    base-url: http://localhost:18083
